theme: jekyll-theme-minimal
title: Nguyet 
url: https://github.com/ngtto/nt.github.io/
baseurl: /nt.github.io
favicon:     "images/favicon.ico"
aboutme: hi, its me
aboutme_photo: https://github.com/ngtto/nt.github.io/blob/main/docs/assets/IMG_2653.png
locales:
    en:
      Aboutme: "About Me"
